### PR TITLE
Add a flag to use the old C++ ABI when compiled with newer GCC.

### PR DESCRIPTION
**Pull request by bdaskalov**
This adds a compile flag which specifies that newer GCC version should use the old ABI when compiling the Tensorflow extension.

### CODE REVIEW

**Comment by bdaskalov** [comment]
@jaredcasper Can you please take a look?

**Comment by jaredcasper** [comment]
Looks okay to me, only suggestion may be to only add the flag if g++ version 5+ is being used.  However, I no longer have write access to this repo (I don't work at Baidu anymore).

**Comment by bdaskalov** [comment]
@jaredcasper  Do you know somebody who could be able to review and merge it?

**Comment by matth** [comment]
Hello, I can confirm this works on Ubuntu 16.04 and fixes the issue raised in #59. Is anybody able to merge this fix so we can install from official master?

**Comment by milani** [comment]
I used this PR to build with gcc-5 on Ubuntu 17.04 and Cuda 8. The following is the errors I received:

```
-- Generating /home/morteza/Experiments/warp-ctc-g++5/build/CMakeFiles/test_gpu.dir/tests/./test_gpu_generated_test_gpu.cu.o                                                                                                                                  
/usr/bin/nvcc /home/morteza/Experiments/warp-ctc-g++5/tests/test_gpu.cu -c -o /home/morteza/Experiments/warp-ctc-g++5/build/CMakeFiles/test_gpu.dir/tests/./test_gpu_generated_test_gpu.cu.o -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-fopenmp\",\"-O2\",\"-g\" -
gencode arch=compute_30,code=sm_30 -O2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 --std=c++11 -Xcompiler -fopenmp -DNVCC -I/usr/include -I/home/morteza/Experiments/warp-ctc-g++5/include
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9218): error: argument of type "const void *" is incompatible with parameter of type "const float *"                                                                                                  
                                                                                                                 
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9229): error: argument of type "const void *" is incompatible with parameter of type "const float *"                              
```

and the list of errors goes on all with the same description.
